services:
  - type: web
    name: emotion-backend
    env: python
    region: singapore
    plan: starter
    buildCommand: "pip install -r render_requirements.txt"
    startCommand: "uvicorn render_app:app --host 0.0.0.0 --port 10000"
  